### ISSUE TITLE
Queue position indication seems wrong

### ISSUE THREAD

**Issue by fatho** [channable/hoff#48] opened 2020-02-24 08:14 UTC
I approved two pull requests in the same repository in quick succession, and on both pull requests Hoff commented 

> waiting for rebase at the front of the queue.

Looking at the source code, I would expect that only one PR is "at the front of the queue", and that the other is "waiting for rebase behind 2 pull requests".

Situation to potentially reproduce:

1. Have one PR that is currently being built by hoff
2. Approve two PRs for merging in quick succession

**Comment by duijf** [comment] 2020-02-24 08:30
Hoff merges approved PRs in order of ascending ID.

So this might be a duplicate of: https://github.com/channable/hoff/issues/25

**Comment by fatho** [comment] 2020-02-24 08:35
I indeed approved the one with the higher ID first, that explains it. If the queue position is not actually stable, maybe we shouldn't print anything at all about the queue position, just something like "the PR is queued for integration".

**Comment by ruuda** [comment] 2020-06-18 08:49
I think there is a bug with counting failed PRs as being in the queue. We could fix that, but probably we should do #53 instead.

**Comment by FPtje** [comment] 2021-07-27 07:26
This was fixed along with the fix for #25

**Closed by FPtje** 2021-07-27 07:26 UTC
Labels: bug
